name: Send monthly email

on:
  schedule:
    # Run the job every month on the first day of the month at 9:00 AM UTC
    - cron: '0 9 1 * *'

jobs:
  send-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.trecydsouza95@gmail.com }}
          password: ${{ secrets.Trecy@1995 }}
          subject: 'Monthly update'
          body: 'Hello, this is your monthly update.'
          to: ${{ secrets.priston.dsouza7@gmail.com }}
          from: ${{ secrets.trecydsouza95@gmail.com }}
        env:
          PASS: ${{ secrets.Trecy@1995 }}


        